- name: Configure MySQL Database Server
  hosts: "{{ hostvars['localhost']['db_instance'].private_ip }}"
  gather_facts: true
  become: true
  roles:
    - mysql_role  # This role should handle MySQL installation and configuration
  vars:
    mysql_root_password: "xxxxx"
    mysql_user: "xxxx"
    mysql_password: "xxx"
    mysql_database: "xxxxx"
